:schedule:
  daily_notification:
    cron: '0 * * * * *'   # Runs once per minute
    class: NotificationWorker
  reminders:
    cron: '0 12 * * * America/Argentina/Buenos_Aires'   # Runs once per day at noon art
    class: ReminderWorker
  first_test_reminder:
    cron: '0 9 * * * America/Argentina/Buenos_Aires'   # Runs once per day at 9am ART, first reminder for completing test
    class: PhotoReminderWorker
    args: [1]
  second_test_reminder:
    cron: '0 19 * * * America/Argentina/Buenos_Aires'   # Runs once per day at 7pm ART, first reminder for completing test
    class: PhotoReminderWorker
    args: [2]
  misssed_reporting_reminder:
    cron: '0 0 * * * *'
    class: MissedReportingReminderWorker
  patient_stats_update:
    cron: '0 0 * * * America/Argentina/Buenos_Aires'   # Runs once per day at midnight Argentina
    class: PatientStatsWorker
    args: [true,0]
