# docker continuous delivery
# deliver docker images to configured repo with tags to match branches and git tags
---
name: Publish Docker
on:
  push:
    branches:
      - develop
      - master
      - prod-id
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git commit
        uses: actions/checkout@master
      - name: Get commit branch
        id: get_branch
        run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Publish to Dockerhub registry
        # todo: pin to hash
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
          name: ${{ github.repository }}
          # configured at repo settings/secrets
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_ACCESS_KEY }}
          tags: "${{ env.branch_name }}"
